### PR TITLE
Add spectests & padding fix

### PR DESCRIPTION
**Pull request by kasey**
This branch adds more complete spectest coverage, running tests across forks (`phase0`/`altair`) and configurations (`minimal`/`mainnet`). Also included is the padding fix for slices of misaligned (not multiples of 32) byte slices, eg `[][]48`. I made a separate branch with the padding commits reverted:
https://github.com/kasey/fastssz/tree/spec-tests-without-padding-fix

 If you run the spectests in the `spec-tests-without-padding-fix` branch, the failures will be apparent -- run `go test -v ./spectests/...` to see failures for:
- `LightClientSnapshot`
- `SyncCommittee`

This branch builds on and replaces the branch in pr 58: https://github.com/ferranbt/fastssz/pull/58
If this PR is accepted, the other one should be closed. Thank you!

### CODE REVIEW

**Comment by kasey** [comment]
Forgot to mention, I haven't been able to track down why BeaconState is failling on both Altair configs, so that type is currently skipped.

**Comment by ferranbt** [comment]
Okay so there is a couple of things to review here. My though was (after our Discord talk) that though #58 fixes the 48 padding issue on your side (Prysm), #59 passes all the tests without any change and that would be the thing to check next.

But this change adds both #58 again (though there might be a zero-memory way to do that padding if necessary) + multiple spec testing in the same PR.

Can you check which spec tests are you using in Prysm, if #59 works for you and then we can see which PRs do we include to support Altair? Later on we can think about the most efficient way to do multiple spec testing.

**Comment by kasey** [comment]
I made a new prysm branch from our altair working tree, and in that branch reverted my changes and pinned the fastssz version to the version in #59 (your `feature-altair` branch). The spectests did pass on that version. However they did not pass using the previously pinned version (90640294cb9c). I thought that was weird so I took a closer look at the diffs, and I realized that you actually do have a change in `feature-altair` that changes the hashing behavior: https://github.com/ferranbt/fastssz/pull/59/files#diff-85a23cc519086060e2e9a6ac3da7b5e51f0d2e33556c8ca7fbd8ed8e42621131R51

It seems like by switching to `PutBytes` for the generated code the problem is solved, because PutBytes checks chunk alignment and adds padding under the covers. So if you get #59 merged, we can use that version. I'll close #58, and leave you to decide how you want to use the spectest code contributed in #60.

**Comment by ferranbt** [comment]
Ok, I will merge #59 and then we can rebase with this PR and add the specs here.

**Comment by kasey** [comment]
Sounds great, thank you

**Pull request closed without merging**
